### ISSUE TITLE
Rotate through a single tab?

### ISSUE THREAD

**Issue by orschiro** [KevinSheedy/chrome-tab-rotate#1]
Dear @KevinSheedy,

This extension is brilliant. 

Thank you!

Question: 

What do you think of an (optional) option to rotate through a single tab?

Yours,

Robert

**Comment by KevinSheedy** [comment]
Hi @orschiro 
I'm afraid I don't understand what you mean by "rotate through a single tab".
Could you clarify? Maybe give an example?
Thanks,
Kevin

**Comment by orschiro** [comment]
Hi Kevin, 

Let's say my list of URLs is:

1. youtube.com
2. reddit.com
3. github.com

I want to load these three URLs sequentially in a single tab. First, load youtube.com. Then upon the click of the extension icon (or after a certain amount of time), open reddit.com in the very same tab, ...

**Comment by KevinSheedy** [comment]
Hi @orschiro 
The reason I didn't do it this way is that the user would be forced to watch the page reload every time the url changes. As page loads typically take approx 3-5 seconds, I felt this was a very bad user experience. Instead, page loads always take place in the background to give a much smoother user experience.

Can you suggest any benefits of loading all the urls in the same tab?

**Comment by orschiro** [comment]
Hi @KevinSheedy,

Thanks for your prompt reply. Very appreciated!

I draw most of my inspiration from this (old) extension: https://chrome.google.com/webstore/detail/url-loader/pehlobngallbbadijocicdimmcpcckhl

The benefits of loading all URLs in the same tab, I believe, is a conceptual one. It provides the user with a session mode. You "loop" through your list of tabs (your tasks) one by one until you are done with your session and all tabs are cleared. 

However, I see your point in terms of tab loading. 

How about the following workflow:

1. Prepare your list of URLs (tabs)
2. Click on the extension icon to start the session
3. Open the first URL in the list in a tab while opening the second URL in the list in a second background tab
4. Click on the extension icon once you are done with the active tab. The tab closes and focus is given to the second tab that was loaded in the background. 
5. Meanwhile, the third URL is loaded in the background to prepare the next tab switch
6. This procedure goes and on and on. 

What do you think?

**Comment by KevinSheedy** [comment]
Hi @orschiro 
I think this is conceptually different from what this plugin was designed for. This plugin was designed to provide a team dashboard on a wall-mounted screen. Once configured, it is designed to have no user interaction, except for turning it on/off.

I think a task manager with user interaction would be better off as a separate plugin. Feel free to fork the code and to make the change yourself.

Regards,
Kevin

**Comment by orschiro** [comment]
Alright, thanks Kevin! :+1:
