### ISSUE TITLE
Apply settings only if changed

### ISSUE THREAD

**Issue by benhubert** [KevinSheedy/chrome-tab-rotate#25]
Hi! I'd like to set `settingsReloadIntervalMinutes` set to `1`, so that the addon fetches the settings every minute, but it seems that this also means that it reloads all tabs every minute, even if `tabReloadIntervalSeconds` is set to `3600`.

Would it be possible to check whether the new settings differ from the already loaded ones and to reload all the tabs only if the settings have been changed?

**Comment by KevinSheedy** [comment]
Hi @benhubert 
This is now fixed in v0.3.0
