### ISSUE TITLE
Problem when opening too many tabs

### ISSUE THREAD

**Issue by dpertuze** [KevinSheedy/chrome-tab-rotate#27]
I am using this extension with Chromium on a Raspberry to display dashboards of different projects.
Actually, I put 8 URLs in the json config file, pointing to the same dashboard server, but to 8 different projects.
It seems like these 8 tabs are, at startup, opened at the same time, and this is the problem: the pages cannot load correctly. I don't know what exactly the problem is, maybe the server cannot proceed all the requests at the same time.

My request is : is it possible, when Tab Rotate starts, to add an option to open all tabs with a delay between them ? (some seconds).

Thanks.

**Comment by KevinSheedy** [comment]
Fix for this available in version 0.2.2 which is now live.
It's now the default behaviour to only load the first two websites on start then load subsequent sites one by one just before they get displayed.

@dpertuze Could you test this on your platform please?

**Comment by KevinSheedy** [comment]
I had to back out this fix as it caused a regression.
I'll try fix it again soon.

**Comment by KevinSheedy** [comment]
Fixed again in 0.3.4
