### ISSUE TITLE
Version 0.3.2 => preview of local config file hangs

### ISSUE THREAD

**Issue by maglub** [KevinSheedy/chrome-tab-rotate#36]
In version 0.1.6 and 0.2.0 this worked.

* OS: Ubuntu 16.04.5 LTS Server, lightdm, i3, chromium 71.0.3578.98 
* OS: Ubuntu 18.0.4.1 LTS Server, lightdm, i3, chromium 71.0.3578.98

Steps to reproduce:

* Remove Crome Tab Rotate version 0.1.6
* Add Version 0.3.2
* Try and load local json file (which can be laded in another tab in the browser)

Expexted result:

* "Success"

Current result:

* The browser hangs forever

![image](https://user-images.githubusercontent.com/2961018/52580360-7485b500-2e28-11e9-9324-519e874c0709.png)

**Comment by KevinSheedy** [comment]
Thanks @maglub 
I've reproduced the problem here.
It's odd, when I test the zip file locally it works fine. But then when I install the same version of the app via the Chrome store I'm getting a CORS error in the console:

```Access to XMLHttpRequest at 'file:///Users/kevin/dev/sandbox_workspace/chrome-tab-rotate/src/config.sample.json' from origin 'chrome-extension://pjgjpabbgnnoohijnillgbckikfkbjed' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.```

The permissions change is still in the manifest.json:

```
  "permissions": [
    "activeTab",
    "storage",
    "https://ajax.googleapis.com/",
    "file://*/",
```

I've tried rebuilding and republishing to the Chrome store to see if that will work. Version 0.3.3 should be live shortly.

**Comment by KevinSheedy** [comment]
Looks like you'll need to enable file access:

1. Right Click on the Tab Rotate Icon
2. Click "Manage Extensions"
3. Enable "Allow access to file URLs"

It seems reasonable that Chrome would require the user to allow access to the file system, however, I thought you'd be prompted to allow this while installing the extension.

**Comment by maglub** [comment]
Works, thanks!

**Comment by maglub** [comment]
I am still batteling this a bit, and it seems like there are talks about allowing policy installed extensions to eventually be possible to configure with this permission set by default.

* https://bugs.chromium.org/p/chromium/issues/detail?id=173640

To install this extension on, for example, Raspbian Buster:

```
sudo mkdir /etc/chromium/policies
sudo mkdir /etc/chromium/policies/managed
sudo mkdir /etc/chromium/policies/recommended

cat<<EOT | sudo tee -a /etc/chromium/policies/managed/my_policy.json
{
  "HomepageLocation": "https://20min.ch",
  "ExtensionInstallForcelist": [
    "pjgjpabbgnnoohijnillgbckikfkbjed;https://clients2.google.com/service/update2/crx"
  ]
}
EOT
```

This will install the Tab Rotate extension next time you start the browser. It will not have access to the local filesystem, and it is not possible to turn it on. But perhaps in an upcoming release of Chromium it will be there.

**Comment by KevinSheedy** [comment]
Hi @maglub 
Is there anything you think I can help with on this?
linux / chrome policy not really my strong suit tbh.

**Comment by maglub** [comment]
Not really. I am also trying to learn how to automate the installation of the plugin, so we are probably on the same page here.

The bug ticket mentioned, probably says it all. There is no way at this time, to give the file permissions that I need for a fully automated installation.

I am currently using the trick mentioned in #26, tar-balling the .config/chromium directory, pushing it to my clients, and starting chromium with "--user-data-dir=/.../somewhereunique", which in turn has been manually configured to use one of my local files. This works particularly well for multi screen setups.

The drawbacks are:

* I have to keep a 20MB blob of config per screen (since I want them to use different config.json files)
* I have to manually point to a config.json file once, and create the tar-ball

Not really your fault, I would say. It is the way Chrome/Chromium works, to fight against malware.
