### ISSUE TITLE
Is it possible to support multiple chrome windows?

### ISSUE THREAD

**Issue by wanglf** [KevinSheedy/chrome-tab-rotate#4]
Seems it only works in a single window,  because rotator settings get synced on every chrome window.

**Comment by KevinSheedy** [comment]
Do you mean to have two windows on the same machine but displaying to two different screens? Each screen displaying a different set of tabs?

This isn't supported at the moment but you could achieve this by installing 'Chrome Canary' which allows you to have a totally separate configuration.

**Comment by wanglf** [comment]
Yes, that's exactly what i mean. 

Thank you very much,  I'll take a look at 'Chrome Canary'.

**Comment by KevinSheedy** [comment]
https://www.chromium.org/getting-involved/dev-channel#TOC-Mac

Here’s a link with info on the different Chrome “channels”. The Beta channel may be a better choice than Canary
