### ISSUE TITLE
[Feat]: Support for confguration by policy (managed storage api)

### ISSUE THREAD

**Issue by Silthus** [KevinSheedy/chrome-tab-rotate#43]
First of thanks for the great plugin! We are currently evaluating this as a perfect solution to display changing tabs for monitoring walls in our company. However there is one issue: the plugin by default must be configured by hand.

It would be awesome if support for the chrome://policy configuration was added.

https://www.chromium.org/administrators/configuring-policy-for-extensions
https://developer.chrome.com/extensions/manifest/storage

The plugin could then be configured via GPO to automatically load a JSON configuration and start after being force deployed to the required computers. This would make it so that the plugin can be used without someone touching the computer.

I am also willing to create a PR for that feature, if wanted.

**Comment by ablanken** [comment]
+1 We'd definitely make use of this feature if it was implemented. Cheers

**Comment by Silthus** [comment]
Since this project is inactive and does not accept PRs, I created my own tab rotate extension focusing on enterprise and zero touch usage: https://github.com/Silthus/chrome-enterprise-tab-rotate
