### ISSUE TITLE
Configuration options renamed

### ISSUE THREAD

**Issue by JBodkin-LH** [KevinSheedy/chrome-tab-rotate#7]
We've been using this plugin to power the wallboards in the office and it appears the recent release has broken our setup. I've had a quick look into the recent commit and I think the issue happens as the variable `settings.source` has been changed to `settings.configSource`. Since our configuration exists from the older version of the plugin, it fails to parse the configuration on startup.

Would you be able to release a new version that checks both variables?

**Comment by KevinSheedy** [comment]
Hi @JBodkin-LH 
I've published a fix for this, V0.0.16
It may take up to an hour to become live on the Chrome Web Store
Would you be able to test it once it does?
Thanks

**Comment by JBodkin-LH** [comment]
Fantastic, that works
