### ISSUE TITLE
Fetching the JSON file from an URL doesn't work anymore

### ISSUE THREAD

**Issue by miniblop** [KevinSheedy/chrome-tab-rotate#83]
I use this plug-in since 1 year and for the last few months it seems that my json file is no longer fetched when opened via its URL.

When I reset to defaut to add the url and test it, it write the right file into the text box but it is not possible to save the config. 

The JSON format is validated.

If you know how to help me,
Thanks in advance

**Comment by KevinSheedy** [comment]
I think this is fixed in version 0.6.1
Let me know if this build doesn't fix your issue
